[tool.black]
line-length = 79
target-version = ['py310']
include = '\.pyi?$'
[tool.isort]
profile = "django"
combine_as_imports = true
include_trailing_comma = true
line_length = 79
multi_line_output = 3
known_first_party = ["config"]
[tool.djlint]
profile = "django"
ignore = "H031"
